name: Deploy to VPS

on:
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VPS_USER: ${{secrets.VPS_USER}}
      VPS_IP: ${{secrets.VPS_IP}}
      VPS_SSH_KEY: ${{secrets.VPS_SSH_KEY}}
      REPO_NAME: ${{secrets.REPO_NAME}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH for VPS
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.VPS_SSH_KEY}}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $VPS_IP >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: SSH into VPS and deploy
        run: |
          ssh $VPS_USER@$VPS_IP << EOF
            if [ -d "$REPO_NAME" ]; then
              echo "Directory exists. Performing git pull."
              cd $REPO_NAME
              git pull
            else
              echo "Directory does not exist. Cloning the repository."
              git clone https://github.com/BenjaminVQE/BoxManagement.git
              cd $REPO_NAME
              echo "--Stop container--"
              docker ps -a --filter "name=boxmanagement" -q | xargs -r docker stop
              echo "--Removing container--"
              docker ps -a --filter "name=boxmanagement" -q | xargs -r docker rm
              echo "--Removing image--"
              docker image rm boxmanagement-php || true
              echo "--Rename .env.example--"
              mv .env.example .env
              echo "--Running container--"
              make dc-up
              echo "--Composer Install--"
              docker exec boxmanagement-php-1 sh -c "composer install"
              echo "--Updating .env variables--"
              sed -i 's/^DB_DATABASE=.*/DB_DATABASE=$DB_NAME/' .env
              sed -i 's/^DB_USERNAME=.*/DB_USERNAME=$DB_USERNAME/' .env
              sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=$DB_PASSWORD/' .env
              docker exec boxmanagement-php-1 sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache"
              docker exec boxmanagement-php-1 sh -c "chmod -R 775 /var/www/storage /var/www/bootstrap/cache"
              docker exec boxmanagement-php-1 sh -c "php artisan key:generate"

            fi

          EOF
